### ISSUE TITLE
Typer todo list

### ISSUE THREAD

**Issue by rognierbenoit** [edukera/archetype-lang#96]
- [x] prefix 'before' keyword, make it works for variables
 - [x] method argument s(manage (`T _ ))
 - [x] label uniqueness
 - [x] transitions
 - [x] enhance reporting for "Operator selection fail" error
 - [x] improve security predicate implem
 - [x] constants/variables must be initialized in the code (fail if not)
 
tests 
  - [x] test_method.arl (without comment)
  - [x] escrow_basic.arl ('price' as init value in formula)
